// Auto-generated from OwnerRez export — update as needed
export interface Review {
  id: number
  guestName: string
  rating: number
  date: string
  text: string
  source: string
}

export const reviews: Review[] = [
  {
    id: 1,
    guestName: "Samantha",
    rating: 5.0,
    date: "2026-03-15",
    text: "Exactly like the pictures! Very close to town, but still felt extremely secluded. Never heard another car. Will return in the future! \u2b50\ufe0f\u2b50\ufe0f\u2b50\ufe0f\u2b50\ufe0f\u2b50\ufe0f",
    source: "Airbnb",
  },
  {
    id: 2,
    guestName: "Caleb",
    rating: 5.0,
    date: "2026-03-12",
    text: "Very professional host and a beautiful place! Everything was communicated It was serene to wake up to the natural sunlight with the Mountain View! Wish we had more time to spend here.",
    source: "Airbnb",
  },
  {
    id: 3,
    guestName: "Chrishell",
    rating: 5.0,
    date: "2026-03-08",
    text: "We absolutely loved our stay during our time in Tennessee! Everything was well put together and spotless. Our favorite part of the BnB was the hot-tub overlook it was very pretty during sunset. The location was perfect, neighbors weren\u2019t too close and attractions were only about a 20 minute drive. I would highly recommend staying here and would definitely stay here again just for the most comfortable king sized bed!",
    source: "Airbnb",
  },
  {
    id: 4,
    guestName: "Darcy",
    rating: 5.0,
    date: "2026-03-04",
    text: "I don't know where to start! Beautiful cabin iwith a beautiful and peaceful view. We didn't want to leave. Anusha and Manesh were responsive and kind in communication. Beautifully decorated and bers were super comfortable. Will definitely come back, if I get the chance.",
    source: "Airbnb",
  },
  {
    id: 5,
    guestName: "Kristen",
    rating: 5.0,
    date: "2026-02-25",
    text: "Absolutely stunning and immaculate property. mostly, all of the little things were thought of by the hosts to make our stay more comfortable and convenient. their guestbook had everything in it.From how to use the coffee pot to local attractions in the area. the backyard was beautiful in the swing seat was my favorite with the fire pit. perfect couples retreat.",
    source: "Airbnb",
  },
  {
    id: 6,
    guestName: "Bridget",
    rating: 5.0,
    date: "2026-02-22",
    text: "10/10 recommend choosing this beautiful home for your stay sevierville,TN. Very kid friendly, beautiful view and clean. Host were responsive and available for any questions during the stay! Our family will be booking again, Thank you!",
    source: "Airbnb",
  },
  {
    id: 7,
    guestName: "Jazzlyn",
    rating: 5.0,
    date: "2026-02-19",
    text: "Beautiful cabin with an amazing view and in a great area.",
    source: "Airbnb",
  },
  {
    id: 8,
    guestName: "Samantha",
    rating: 5.0,
    date: "2026-02-18",
    text: "The cabin was a perfect getaway. Definitely gives the feeling of being secluded in the mountains. Recommend Pawpaws catfish for food. The scenic helicopter ride was beautiful and riding utvs in the mountain. There is alot do and explore close to the area. Also Ole smokey distillery is a must in town.",
    source: "Airbnb",
  },
  {
    id: 9,
    guestName: "Jaxon",
    rating: 5.0,
    date: "2026-02-09",
    text: "Great house and really close to everything",
    source: "Airbnb",
  },
  {
    id: 10,
    guestName: "Felix Javier",
    rating: 5.0,
    date: "2026-02-04",
    text: "Love the Place !! Was super comfortable and Peaceful!! We enjoy seeing the views in the morning and afternoons!! Was Perfect for us and my kids , we really enjoy everything!!",
    source: "Airbnb",
  },
  {
    id: 11,
    guestName: "Kyle",
    rating: 5.0,
    date: "2026-01-24",
    text: "Anusha & Manesh were great hosts & their place was lovely! We absolutely enjoyed it! Will be recommending!!",
    source: "Airbnb",
  },
  {
    id: 12,
    guestName: "Owen",
    rating: 5.0,
    date: "2026-01-22",
    text: "Amazing place! The views off the balcony were truly amazing! I\u2019ve been vacationing in the smokies my whole life and this was the best place I\u2019ve stayed!",
    source: "Airbnb",
  },
  {
    id: 13,
    guestName: "Jadyn",
    rating: 5.0,
    date: "2026-01-22",
    text: "The cabin was very nice and amazing. We had a very wonderful experience. Very nice hosts, very responsive and respectful as well.",
    source: "Airbnb",
  },
  {
    id: 14,
    guestName: "Beau",
    rating: 5.0,
    date: "2026-01-11",
    text: "Wonderful experience and most importantly, an easy and seamless check in process, a beautiful space to enjoy our vacation and a caring and helpful host. Highly recommended for any special trip!",
    source: "Airbnb",
  },
  {
    id: 15,
    guestName: "John",
    rating: 5.0,
    date: "2026-01-08",
    text: "Perfectly located close to everything but tucked away and private at the same time with easy parking! Beautiful clean cabin with comfortable beds and high quality linens! Everything was very clean and was just like the pictures and description. Check in and out was super easy and will definitely stay here again next trip!",
    source: "Airbnb",
  },
  {
    id: 16,
    guestName: "Mason",
    rating: 5.0,
    date: "2026-01-04",
    text: "Anusha & Manesh were phenomenal hosts with a beautiful home. Happy I had the opportunity to stay somewhere so cool! Will definitely be back again!!",
    source: "Airbnb",
  },
  {
    id: 17,
    guestName: "Christopher",
    rating: 5.0,
    date: "2026-01-03",
    text: "This was my family's first time to the area and we were not disappointed, especially with this beautiful home! The views from the porch were amazing and between the hot tub and the swings, its hard not to relax. The furniture and the beds were comfortable, the house was spotless and it was stocked with everything you could need. The owners were very responsive and helpful and also gave fantastic instructions and some good local recommendations. We were very happy with our first stay in Sevierville, absolutely 5 starts for the home and experience!",
    source: "Airbnb",
  },
  {
    id: 18,
    guestName: "Saiesh",
    rating: 5.0,
    date: "2026-01-02",
    text: "Cozy cabin with excellent views and amenities. Fantastic hosts. Highly recommended!",
    source: "Airbnb",
  },
  {
    id: 19,
    guestName: "Jeremy",
    rating: 5.0,
    date: "2026-01-01",
    text: "Gorgeous cabin just minutes from downtown Pigeon Forge",
    source: "Airbnb",
  },
  {
    id: 20,
    guestName: "Meagan",
    rating: 5.0,
    date: "2025-12-27",
    text: "Beautiful cabin with amazing mountain views. Peaceful and quiet but a short distance and easy drive away from all the attractions. Hosts were super helpful and friendly. Our family had an amazing time and will definitely be back!",
    source: "Airbnb",
  },
  {
    id: 21,
    guestName: "Kayla",
    rating: 5.0,
    date: "2025-12-20",
    text: "Our family had the best time! The host was amazing, they responded quickly to all our questions. When we visit Tennessee again we will book with Anusha and Manesh.",
    source: "Airbnb",
  },
  {
    id: 22,
    guestName: "Jessica",
    rating: 5.0,
    date: "2025-12-14",
    text: "This is such a perfect place! I spend hours searching for the perfect vacation place, so do yourself a favor, stop searching and pick this one! I will stay here again! Loved every second of this stay!",
    source: "Airbnb",
  },
  {
    id: 23,
    guestName: "Heather",
    rating: 5.0,
    date: "2025-12-10",
    text: "Beautiful surroundings with such kind hosts!",
    source: "Airbnb",
  },
  {
    id: 24,
    guestName: "Tharun",
    rating: 5.0,
    date: "2025-12-08",
    text: "I had a wonderful stay! The place has amazing views \u2014 truly the highlight of the visit. The host was extremely responsive and helpful throughout, which made the experience smooth and comfortable. Even though it was a short stay, everything was perfect. I\u2019ll surely be back to this place with my family on my next trip. Highly recommend this Airbnb!",
    source: "Airbnb",
  },
  {
    id: 25,
    guestName: "Courtney",
    rating: 5.0,
    date: "2025-12-06",
    text: "We had a wonderful stay. The home was very clean and just as advertised. Would love to visit again.",
    source: "Airbnb",
  },
  {
    id: 26,
    guestName: "Alexander",
    rating: 5.0,
    date: "2025-12-02",
    text: "El lugar es muy tranquilo y bonito que te sientes en casa",
    source: "Airbnb",
  },
  {
    id: 27,
    guestName: "Ashly",
    rating: 5.0,
    date: "2025-11-29",
    text: "We loved our stay! The cabin is beautiful, clean, cozy, and very relaxing. It feels private while still being close to nearby places, making it perfect for a peaceful getaway. Response time was quick when we messaged, which we appreciated. It truly felt like home. We would definitely recommend.",
    source: "Airbnb",
  },
  {
    id: 28,
    guestName: "Charles",
    rating: 5.0,
    date: "2025-11-25",
    text: "We chose this place for our honeymoon, with a stay of 6 days. The place was amazing and as described. The hot-tub was clean and functioned perfectly (high jets, remove/replace cover for uses) in the cold nights/mornings. The two bedroom options were perfect with one located in the roof area with a beautiful view, and a separate room on the floor area. All areas were clean on arrival. We did end up using the small picnic grill in the back (bought charcoal, lighter fluid, etc) and were able to discard old charcoal in a provided pail. We drove a Volkswagen Atlas, and there is a slight incline to the driveway, but it is completely manageable. As an aside, the location is perfect and groundlevel compared to other cabins that are located higher up in the mountains (which means a longer/slower drive to make it down and to get to stores nearby (walmart, kroger, publix). We highly recommend Mel's diner! Overall, this is a great cabin, and we will be back and recommend it to others!",
    source: "Airbnb",
  },
  {
    id: 29,
    guestName: "Vivian",
    rating: 5.0,
    date: "2025-11-20",
    text: "Beautiful view with a cozy home!",
    source: "Airbnb",
  },
  {
    id: 30,
    guestName: "Lauren",
    rating: 5.0,
    date: "2025-11-09",
    text: "We had an amazing stay at this Gatlinburg cabin! The place was spotless, cozy, and exactly as described. The views were absolutely beautiful especially in the mornings with the fog rolling over the mountains!!!!",
    source: "Airbnb",
  },
  {
    id: 31,
    guestName: "Malik",
    rating: 5.0,
    date: "2025-11-09",
    text: "My wife and I truly enjoyed our stay here it was such a relaxing and peaceful getaway. The cabin had a super homey feel, and the fire pit was an awesome touch. We especially loved that the hot tub was enclosed it made it even more enjoyable and private. The space is perfect for a couple\u2019s retreat, but there\u2019s also plenty of room for family or friends if you\u2019re visiting with a group. The mountain views were absolutely gorgeous, and overall this place was just amazing. Definitely worth staying here and checking out for yourself!",
    source: "Airbnb",
  },
  {
    id: 32,
    guestName: "Leo",
    rating: 5.0,
    date: "2025-11-01",
    text: "Beautiful cabin both inside and out. Ideal location with stunning views.",
    source: "Airbnb",
  },
  {
    id: 33,
    guestName: "Shannon",
    rating: 5.0,
    date: "2025-10-29",
    text: "House was clean and close to most everything. Host sent us a guide before our trip and it was very helpful.",
    source: "Airbnb",
  },
  {
    id: 34,
    guestName: "Marian",
    rating: 5.0,
    date: "2025-10-24",
    text: "Great place to stay! Went here for our honeymoon and it was wonderful. If we weren\u2019t visiting a local attraction, we were enjoying the hot tub or the fire pit. We were very sad to leave this place. It was incredible and we loved it very much.",
    source: "Airbnb",
  },
  {
    id: 35,
    guestName: "Luis",
    rating: 5.0,
    date: "2025-10-19",
    text: "One of the cleanest airbnbs we have been too, great location, great view, would return again in the future",
    source: "Airbnb",
  },
  {
    id: 36,
    guestName: "Devi",
    rating: 5.0,
    date: "2025-10-16",
    text: "Special thanks to Anusha & Manesh for their lovely cabin! It was in a perfect location within all of the local attractions, but still secluded enough to enjoy the serene Mountain Views without being disturbed. They were extremely responsive to our messages as well. Would highly recommend and will be reaching out to them the next time we are in town!",
    source: "Airbnb",
  },
  {
    id: 37,
    guestName: "Christian",
    rating: 5.0,
    date: "2025-10-08",
    text: "Very nice cabin. Woke up to wild turkeys in the front yard. And the beds were the most comfortable ever.",
    source: "Airbnb",
  },
  {
    id: 38,
    guestName: "Haven",
    rating: 5.0,
    date: "2025-10-07",
    text: "Anusha and Manesh have a great place. It\u2019s in a great area and pretty secluded. The house was very clean. The bed and comforter were so comfortable. The view is amazing.",
    source: "Airbnb",
  },
  {
    id: 39,
    guestName: "Billi-Jo",
    rating: 5.0,
    date: "2025-09-28",
    text: "We had a lovely time with friends. The cabin was clean and the beds comfortable. The host was super responsive and very kind. A joy to work with. Thankfully the roads to the cabin were easy to navigate. Close enough to amenities but still very quiet and peaceful. If you like a peaceful setting with a nice view but want to avoid scary switchback roads this place is for you.",
    source: "Airbnb",
  },
  {
    id: 40,
    guestName: "Bill",
    rating: 5.0,
    date: "2025-09-24",
    text: "Cabin looked just like pics. Hosts very responsive. Had a great stay.",
    source: "Airbnb",
  },
  {
    id: 41,
    guestName: "Brynn",
    rating: 5.0,
    date: "2025-09-23",
    text: "Spent our 5 year anniversary here. We visited local shopping and parks but our favorite memory was spending the mornings in the hot tub with coffee. We will definitely be back!",
    source: "Airbnb",
  },
  {
    id: 42,
    guestName: "Cassandra",
    rating: 5.0,
    date: "2025-09-22",
    text: "Lovely stay. Tastefully decorated and furniture in good condition. Comfy beds. VERY responsive hosts. Nice outdoor seating.",
    source: "Airbnb",
  },
  {
    id: 43,
    guestName: "Joshua",
    rating: 5.0,
    date: "2025-09-16",
    text: "Great stay! Only regret was not having more time to be there.",
    source: "Airbnb",
  },
  {
    id: 44,
    guestName: "Sarah",
    rating: 5.0,
    date: "2025-09-14",
    text: "Beautiful cabin for a relaxing getaway in the mountains!",
    source: "Airbnb",
  },
  {
    id: 45,
    guestName: "Christa",
    rating: 5.0,
    date: "2025-09-09",
    text: "We only stayed one night as we were in town for the Vols game. I wish we couod have stayed longer. Don't hesitate to book. Beds are fabulous. Host quickly responds to any questions. We arrived late and I had a response in 30 seconds. The cabin was so clean. It smelled amazing and no dirt or dust anywhere. The decor is beautiful. Its so close to town with no steep hills to climb to get there. We will most definetly return. Loved it !",
    source: "Airbnb",
  },
  {
    id: 46,
    guestName: "Becky",
    rating: 5.0,
    date: "2025-08-31",
    text: "My family\u2019s stay was wonderful! The house and view were beautiful and we felt right at home from the moment we walked inside.",
    source: "Airbnb",
  },
  {
    id: 47,
    guestName: "Amanda",
    rating: 5.0,
    date: "2025-08-30",
    text: "Beautiful and quiet location while still being conveniently located close to many attractions and stores in the area. Host was very responsive and accommodating.",
    source: "Vrbo",
  },
  {
    id: 48,
    guestName: "Ashwin Kumar",
    rating: 5.0,
    date: "2025-08-28",
    text: "We had an absolutely wonderful stay at this cabin. The place was even better than described in the listing, it was spotless, cozy and full of charm. The property has such great views, which made the experience even more memorable. On top of that, the host was super responsive and made everything smooth from check-in to check-out. Highly recommend this spot if you\u2019re looking for a perfect getaway!",
    source: "Airbnb",
  },
  {
    id: 49,
    guestName: "Isabella",
    rating: 5.0,
    date: "2025-08-25",
    text: "Such an amazing getaway! We were fine with just staying in the cabin because of how nice and peaceful it was. We are already planning to come back :)",
    source: "Airbnb",
  },
  {
    id: 50,
    guestName: "Crystal",
    rating: 5.0,
    date: "2025-08-20",
    text: "Beautiful cabin. The beds and linens were exquisite. Very comfortable. Highly recommend.",
    source: "Airbnb",
  },
  {
    id: 51,
    guestName: "John",
    rating: 5.0,
    date: "2025-08-19",
    text: "We had an absolutely wonderful stay! The cabin was spotless, cozy, and perfectly located\u2014just minutes from all attractions in Pigeon Forge and Gatlinburg areas, yet tucked away enough to feel peaceful and private. The hosts thought of everything: comfy beds, a well-stocked kitchen, and thoughtful touches that made us feel right at home. We especially loved relaxing on the porch and enjoying the mountain views in the hot tub after a busy day exploring. Communication with the Anusha and Manesh was quick and friendly, making check-in a breeze. We can\u2019t recommend this place enough and would definitely stay here again! John & Jean",
    source: "Airbnb",
  },
  {
    id: 52,
    guestName: "Brianna",
    rating: 5.0,
    date: "2025-08-15",
    text: "We had such a great time at the cabin! It has stunning views! The location was great and close to so many things to do.",
    source: "Airbnb",
  },
  {
    id: 53,
    guestName: "Jerry",
    rating: 5.0,
    date: "2025-08-15",
    text: "This home had breathtaking views, was spotless, and came with one of the most accommodating hosts we\u2019ve ever met. We were in another cabin and wanted to extend our stay, but it was booked. This host went above and beyond to have this home ready for us by 10:30 AM. My kids loved the arcade games, the swings by the fire pit, and of course, the amazing views. We will absolutely be back!",
    source: "Airbnb",
  },
  {
    id: 54,
    guestName: "Carlye",
    rating: 5.0,
    date: "2025-08-11",
    text: "Truly a home away from home. We throughly enjoyed this cabin. The cabin was very homey and had all of the needed amenities. The hosts were also very responsive, and set us up for success! No complaints! The driveway is very steep and there\u2019s a flight of stairs to the entrance, so keep this in mind in the winter and if accessibility is a concern.",
    source: "Airbnb",
  },
  {
    id: 55,
    guestName: "Ryan",
    rating: 5.0,
    date: "2025-08-08",
    text: "beautiful view!!",
    source: "Airbnb",
  },
  {
    id: 56,
    guestName: "Abdulla",
    rating: 5.0,
    date: "2025-08-04",
    text: "We recently enjoyed a fantastic staycation at this charming cabin, and we couldn't be more thrilled with our experience. From the moment we arrived, our host made us feel welcome with their warm hospitality and attention to detail. The cabin itself was immaculately clean, showcasing the dedication to maintaining a beautiful environment for guests. Every corner was spotless, which truly enhanced our overall comfort and relaxation. The host went above and beyond to ensure we had everything we needed, providing thoughtful recommendations for local attractions and activities. Their friendly demeanor and excellent communication made our stay even more enjoyable. Overall, we highly recommend this location to anyone looking for a peaceful getaway. Thank you for making our staycation wonderful! We look forward to returning in the future.",
    source: "Airbnb",
  },
  {
    id: 57,
    guestName: "Amy",
    rating: 5.0,
    date: "2025-08-02",
    text: "Enjoyed our stay! Great views and very peaceful. Good location to see all the things we wanted to see and do!",
    source: "Airbnb",
  },
  {
    id: 58,
    guestName: "Daniel",
    rating: 5.0,
    date: "2025-07-28",
    text: "Cabin was clean and looked just like the pictures the view from the balcony was amazing. I wish I would have choosen a longer stay to enjoy the view and fire pit more. The coffee nook is also a fantastic touch. Host was very responsive.",
    source: "Airbnb",
  },
  {
    id: 59,
    guestName: "Matt",
    rating: 5.0,
    date: "2025-07-27",
    text: "The cabin was perfect for what we needed.",
    source: "Airbnb",
  },
  {
    id: 60,
    guestName: "Brandon",
    rating: 5.0,
    date: "2025-07-18",
    text: "My family and I recently had the pleasure of staying at this incredible cabin tucked away in the Smoky Mountains, and I can confidently say it was one of the best experiences I've ever had! From the moment we arrived, we were greeted by stunning views that took our breath away. The cabin is beautifully designed and impeccably maintained, blending rustic charm with modern amenities. Every detail has been thoughtfully considered, from the cozy living area with its inviting fireplace to the fully equipped kitchen that made cooking a joy. The bedrooms are spacious and comfortable, providing a perfect retreat after a day of exploring. What truly sets this cabin apart are the amazing amenities. We enjoyed the hot tub under the stars, the string lights on the balconies that then lead down to the cozy firepit area, sipping coffee in the mornings looking out at the \u201csmoky\u201d rise, and the game room entertained our kids indoors when the day was done. We hope to visit again soon!",
    source: "Airbnb",
  },
  {
    id: 61,
    guestName: "Lisa",
    rating: 5.0,
    date: "2025-07-14",
    text: "This home was beautiful and we are looking forward to a return trip. It was so peaceful in the mountains and the patio and outdoor fire pit was perfect for a relaxing weekend. Thanks for a great weekend!",
    source: "Airbnb",
  },
  {
    id: 62,
    guestName: "Cecilia",
    rating: 5.0,
    date: "2025-07-11",
    text: "Had a great stay at the bluff haven cabin. Perfect for our family of four. The host\u2019s were very quick to respond even after hours. We were very happy with our stay and would be very happy to come back again!",
    source: "Airbnb",
  },
  {
    id: 63,
    guestName: "Anthony",
    rating: 5.0,
    date: "2025-07-10",
    text: "Very nice host, great place to stay in the middle of the moutains. I recommend 100%",
    source: "Airbnb",
  },
  {
    id: 64,
    guestName: "Martina",
    rating: 5.0,
    date: "2025-07-07",
    text: "Good for a couple and kids or two couples",
    source: "Airbnb",
  },
  {
    id: 65,
    guestName: "Clinton",
    rating: 5.0,
    date: "2025-07-02",
    text: "This place is exactly what you want when you visit Gatlinburg and Pigeon Forge. It has the cabin feel you want away from the touristy areas yet a short drive back to civilization. The view from the hot tub and porch is amazing. The fire pit area is so relaxing. Anusha and Manesh reach out and more than happy to help with anything. Will definitely try to stay here again hopefully for a fall trip.",
    source: "Airbnb",
  },
  {
    id: 66,
    guestName: "Aneesh",
    rating: 5.0,
    date: "2025-06-26",
    text: "Our Stay at Bluff Haven Retreat was absolutely incredible! The mountain views from the cabin were simply breathtaking. We adored the private hot tub and cozy fireplace. With amazing amenities like the gourmet coffee bar and a perfect location near Pigeon Forge and Dollywood, it truly is a five-star escape. Highly recommend for creating unforgettable memories!",
    source: "Airbnb",
  },
  {
    id: 67,
    guestName: "Zachary",
    rating: 5.0,
    date: "2025-06-23",
    text: "Outstanding stay as described. Loved this area and this place!",
    source: "Airbnb",
  },
]
